### ISSUE TITLE
Output Docker Build

### ISSUE THREAD

**Issue by CajuCLC** [geerlingguy/ansible-role-ecr_container_build#12]
It would be nice to actually see what's happening just like when you run docker build. That way if something fails we are aware where it failed.
Is it possible?

**Comment by siru88** [comment]
you can see the output when u use -vvv option while running ansible-playbook.

Eg:

`ansible-playbook -vvv docker-build.yml  `

**Comment by geerlingguy** [comment]
Unfortunately this feature is not something that I'd be able to do in this role; instead, it's an upstream Ansible issue. The `docker_image` module does store the build log for debugging (e.g. run with `-vvvv`) or when it fails, but in real-time Ansible doesn't stream logs to the controller. See this proposal for information about the potential for Ansible to stream log output from modules in realtime... someday https://github.com/ansible/proposals/issues/92

**Comment by CajuCLC** [comment]
It's all good.
I just saved the output somewhere else:
RUN command >> somelogfile.log
